### PR TITLE
Add `aeon` to `src` as a git subtree

### PR DESCRIPTION
**Pull request by RyanGibb**

### CODE REVIEW

**Comment by RyanGibb** [comment]
Can be built with `PATH=./_obj/bin:$PATH dune build @@src/aeon/install`.

**Comment by RyanGibb** [comment]
The makefile also picks it up with `dune build @install`

**Comment by patricoferris** [comment]
Sorry @RyanGibb, if you could just check this still builds after #4 happy to merge

**Comment by RyanGibb** [comment]
Thanks Patrick! I'll give this a check when I have a minute

**Comment by RyanGibb** [comment]
Closed in favor of https://github.com/avsm/eeww/pull/5

**Pull request closed without merging**
