### PR TITLE
Add `aeon` to `src` as a git subtree

### PR DESCRIPTION
**Pull request by RyanGibb**
See https://github.com/avsm/eeww/pull/5

### CODE REVIEW

**Comment by RyanGibb** [comment]
Required:
- removing aeon vendored sources
- updating ipaddr for https://github.com/mirage/ocaml-ipaddr/pull/117
- pulling in tuntap and lru
- adding a small patch to dns to allow callbacks: https://github.com/avsm/eeww/pull/7/commits/36a2133d1b40dfa24498ccdcdb58c2263ba7893c

**Comment by RyanGibb** [comment]
Should I be squashing git subtree operations? Updating ipaddr seems to have pulled in a lot of commits

**Comment by avsm** [comment]
No need -- the fun of subtree is that it keeps all the intermediate commits of the subtrees!

**Comment by RyanGibb** [comment]
It looks like this has [broken the macos build](https://github.com/avsm/eeww/actions/runs/5054681554/jobs/9069896563) due to shell over DNS (SoD)'s dependency on `Eio_linux` for [process support](https://github.com/ocaml-multicore/eio/pull/472).

Using [cross platform support](https://github.com/ocaml-multicore/eio/pull/499) should fix this, but I should probably also upstream the [PTY bindings](https://github.com/ocaml-multicore/eio/pull/435#issuecomment-1466833565).

**Pull request merged**
